### ISSUE TITLE
Feature request: Pass the name from GetSnapshot into the final profile

### ISSUE THREAD

**Issue by stevejgordon** [JetBrains/profiler-api#1]
Today, when you call GetSnapshot passing a name, that argument is commented as currently not used. It would really handy if that was the label used for the snapshot such that I can easily identify the various snapshots I have triggered from code. Would this be possible to implement?

```c#
MemoryProfiler.CollectAllocations(true);
MemoryProfiler.GetSnapshot("start");

var config = new TransportConfiguration(new Uri("http://localhost:9200"), new ElasticsearchProductRegistration());
var transport = new Transport(config);
_ = await transport.GetAsync<VoidResponse>("/");

MemoryProfiler.GetSnapshot("before-many-requests");

for (var i = 0; i < 1_000; i++) _ = await transport.GetAsync<VoidResponse>("/");

MemoryProfiler.GetSnapshot("after-many-requests");
```

![image](https://user-images.githubusercontent.com/3669103/124892037-688a8700-dfd1-11eb-8c7f-4cdc465db071.png)

**Comment by ww898** [comment]
Hi @stevejgordon, we already have the ticket about that https://youtrack.jetbrains.com/issue/PROF-706

**Comment by stevejgordon** [comment]
Hi @ww898 - Okay thanks. Glad it's on the tracker as I'd find it very useful. I upvoted there!

**Comment by ww898** [comment]
Fixed
